### ISSUE TITLE
Add open-vm-tools

### ISSUE THREAD

**Issue by dcode** [rocknsm/rock-createiso#24]
If installing RockNSM in a vmware hypervisor, we need to install open-vmtools and at a minimum have it available in the offline repo snapshot in `/srv/rocknsm`.

**Comment by jeffgeiger** [comment]
Within the kickstart:
```
virt=$(sudo virt-what)
if [[ ! $virt == "" ]]; then
  yum install open-vm-tools
fi
```

**Comment by spartan782** [comment]
https://github.com/rocknsm/rock-createiso/blob/985ce790ae81b439fec055797fcfd28b4b6eb191/ks/manual.ks#L95-L99

Here is what was implemented but it doesn't appear to be working.

**Comment by spartan782** [comment]
I think the issue is that `virt-what` needs to run as root.

**Comment by peasead** [comment]
`virt-what: this script must be run as root`

**Comment by peasead** [comment]
```
virt=$(sudo virt-what)
if [[ ! $virt == "" ]]; then sudo yum install open-vm-tools -y; fi
```
This starts to work, but then
```
The GPG keys listed for the "ROCKNSM Local Repository" repository are already installed but they are not correct for this package.
Check that the correct key URLs are configured for this repository.


 Failing package is: libmspack-0.7-0.1.alpha.el7.x86_64
 GPG Keys are configured as: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-RockNSM-2
```
