### ISSUE TITLE
UEFI installs fail

### ISSUE THREAD

**Issue by dcode** [rocknsm/rock-createiso#33]
During the installer setup, anaconda fails to write the bootloader config. Going to the terminal on tmux window 5 (program-log), I see this.

![image](https://user-images.githubusercontent.com/171574/52820604-00d6e880-3072-11e9-9cad-3df8572cfe52.png)

Seemingly the fedora version of something got installed and is looking for a directory that doesn't exist. Manually changing that command to use `centos` allows for the install to complete as expected.

**Comment by dcode** [comment]
This seems related: https://bugzilla.redhat.com/show_bug.cgi?id=1328787

**Comment by dcode** [comment]
Sheeit...  https://github.com/rocknsm/rock-createiso/blob/master/templates/grub.cfg.j2#L42
Changing and pushing.

**Comment by jeffgeiger** [comment]
`--class` in GRUB doesn't do it.

https://unix.stackexchange.com/questions/163985/whats-the-purpose-of-the-class-option-in-grubs-menuentry

**Comment by dcode** [comment]
Fixed in a8e2974
