### ISSUE TITLE
Default filesystem is ext4 for some reason

### ISSUE THREAD

**Issue by dcode** [rocknsm/rock-createiso#34]
This is likely related to #33. The default filesystem on Fedora is ext4, while on CentOS it is XFS. We need to get back to the XFS filesystem, which allows us to use quotas for things like pcap retention.

**Comment by jeffgeiger** [comment]
Added explicit declaration of xfs. Doesn't address root cause though.

https://github.com/rocknsm/rock-createiso/commit/1ff74b2af05fe855818503534784120d12420557

**Comment by jeffgeiger** [comment]
That worked. #33 still needs solved, but this bandaid works for now.
