### ISSUE TITLE
Rsync overrides time on public mirror

### ISSUE THREAD

**Issue by spartan782** [rocknsm/rock-createiso#37]
https://github.com/rocknsm/rock-createiso/blob/12d9f88c69a4116dfb6d35b2cf6e6072bdffc0b1/concourse/upload.sh#L20-L21

Needs to be addressed eventually. Not a critical error but this could potentially cause issues with the hourly cron job to clean up old testing ISO's.

**Comment by dcode** [comment]
Fixed this in fcfcb6e
