### ISSUE TITLE
Push stable packages to PackageCloud

### ISSUE THREAD

**Issue by dcode** [rocknsm/rock-createiso#39]
This is one of the final things. Then the gold release ISO can be cut without testing repo.

**Comment by peasead** [comment]
Is this still an issue after all of the package updates that went out over the weekend?

**Comment by dcode** [comment]
@peasead yes. We're ready to do it now.

Need to run `offline-snapshot` but only enable `rock-testing` and `rock-2.2`. That will download and sign all the things. Then we push the signed packages to Package Cloud 2.3.
