### ISSUE TITLE
Ansible doesn't run on second play

### ISSUE THREAD

**Issue by spartan782** [rocknsm/rock-createiso#59]
When running the `master-iso.sh` when it gets to the ansible portion it will fail if you run it twice.   This is only an issue when you sign packages and they either partially download or all download and get signed. Once these conditions are met and you want to run the script again for any reason it will crash out in `download packages` task. 

https://github.com/rocknsm/rock-createiso/blob/9144b22e1b911a1b679621f2ff128de7ffa03642/ansible/roles/common/tasks/main.yml#L11-L18

The out put from ansible is below.
```
TASK [common : download packages] **********************************************************************************************************************************************************************************************************************************************
task path: /home/admin/rock-createiso/ansible/roles/common/tasks/main.yml:11
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1554392843.21-207182491353216 `" && echo ansible-tmp-1554392843.21-207182491353216="` echo /root/.ansible/tmp/ansible-tmp-1554392843.21-207182491353216 `" ) && sleep 0'
Using module file /home/admin/rock-createiso/ansible/roles/common/library/repobuilder.py
<127.0.0.1> PUT /root/.ansible/tmp/ansible-local-36132nxq0YE/tmpNU27M_ TO /root/.ansible/tmp/ansible-tmp-1554392843.21-207182491353216/AnsiballZ_repobuilder.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1554392843.21-207182491353216/ /root/.ansible/tmp/ansible-tmp-1554392843.21-207182491353216/AnsiballZ_repobuilder.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 /root/.ansible/tmp/ansible-tmp-1554392843.21-207182491353216/AnsiballZ_repobuilder.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1554392843.21-207182491353216/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1554392843.21-207182491353216/AnsiballZ_repobuilder.py", line 113, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1554392843.21-207182491353216/AnsiballZ_repobuilder.py", line 105, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1554392843.21-207182491353216/AnsiballZ_repobuilder.py", line 48, in invoke_module
    imp.load_module('__main__', mod, module, MOD_DESC)
  File "/tmp/ansible_repobuilder_payload_idX4fO/__main__.py", line 417, in <module>
  File "/tmp/ansible_repobuilder_payload_idX4fO/__main__.py", line 405, in main
  File "/usr/lib/python2.7/site-packages/yum/yumRepo.py", line 1075, in getPackage
    **kwargs
  File "/usr/lib/python2.7/site-packages/yum/yumRepo.py", line 1042, in _getFile
    raise e
yum.Errors.NoMoreMirrorsRepoError: failure: Packages/GConf2-3.2.6-8.el7.x86_64.rpm from base: [Errno 256] No more mirrors to try.
http://mirror.centos.org/centos/7/os/x86_64/Packages/GConf2-3.2.6-8.el7.x86_64.rpm: [Errno 14] HTTP Error 416 - Requested Range Not Satisfiable

fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1554392843.21-207182491353216/AnsiballZ_repobuilder.py\", line 113, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1554392843.21-207182491353216/AnsiballZ_repobuilder.py\", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1554392843.21-207182491353216/AnsiballZ_repobuilder.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_repobuilder_payload_idX4fO/__main__.py\", line 417, in <module>\n  File \"/tmp/ansible_repobuilder_payload_idX4fO/__main__.py\", line 405, in main\n  File \"/usr/lib/python2.7/site-packages/yum/yumRepo.py\", line 1075, in getPackage\n    **kwargs\n  File \"/usr/lib/python2.7/site-packages/yum/yumRepo.py\", line 1042, in _getFile\n    raise e\nyum.Errors.NoMoreMirrorsRepoError: failure: Packages/GConf2-3.2.6-8.el7.x86_64.rpm from base: [Errno 256] No more mirrors to try.\nhttp://mirror.centos.org/centos/7/os/x86_64/Packages/GConf2-3.2.6-8.el7.x86_64.rpm: [Errno 14] HTTP Error 416 - Requested Range Not Satisfiable\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
	to retry, use: --limit @/home/admin/rock-createiso/ansible/offline-snapshot.retry

PLAY RECAP *********************************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=1
```

It is possible to work around this locally by simply deleting the packages previously signed and downloaded. This works but is not desired as it requires redownloading all the things.. 

Steps to reproduce.
1. Run the master-iso script with a gpg key
  - ./master-iso.sh -s ${INPUT_ISO} -o output.iso -g '${KEY_NAME}' -p '${KEY_PASSWORD}' -i ${KEY_PATH}
2. Repeat step 1 after completion

**Comment by dcode** [comment]
I think the API that repobuilder uses can generate a list of URLs rather than actually do the downloads. If so, we can take the filename of the URL and compare it with files on disk. To do it correctly, we need to either know the size of the upstream RPM via the API, and/or we need to check the integrity of the RPM on disk, which the file format has built in.

**Comment by spartan782** [comment]
So I am not a 100% sure but pretty sure that is what I am attempting to do already. This should just a list of all the packages that user requested.

https://github.com/rocknsm/rock-createiso/blob/f71c3e86d02bc52c69418917f64f8f1ccb3bee5e/ansible/roles/common/library/repobuilder.py#L336-L345

This finds all the dependancies for the requested packages from the user.

https://github.com/rocknsm/rock-createiso/blob/f71c3e86d02bc52c69418917f64f8f1ccb3bee5e/ansible/roles/common/library/repobuilder.py#L362-L374

This then downloads all the things that are in the tree that is created.

https://github.com/rocknsm/rock-createiso/blob/f71c3e86d02bc52c69418917f64f8f1ccb3bee5e/ansible/roles/common/library/repobuilder.py#L387-L412

Specifically this should be checking the currently downloaded package on the system and then skip it. 
https://github.com/rocknsm/rock-createiso/blob/f71c3e86d02bc52c69418917f64f8f1ccb3bee5e/ansible/roles/common/library/repobuilder.py#L393-L395

I think the error is beyond the skip and possibly on the YUM side of the house. This works perfectly fine if you don't sign the packages with a custom key. As soon as you sign the packages however it breaks. I dunno if yum is doing something different internally when checking because the packages locally are now signed differently than the ones it is seeing upstream?

**Comment by spartan782** [comment]
Closing as repobuilder wont be used. Replacing with the built in dnf module. Will open a new issue the signing fails using dnf module.
